name: cf_partner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  path_provider: ^2.1.1
  path: ^1.8.3
  json_annotation: ^4.8.1
  provider: ^6.1.1
  dio: ^5.3.3
  url_launcher: ^6.2.5
  file_picker: ^8.0.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  flutter_launcher_icons: "^0.13.1"
  msix: ^3.16.7

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "res/images/icon.png"
    icon_size: 256

flutter:
  uses-material-design: true

msix_config:
  display_name: CF Partner
  identity_name: YuiHrsw.CFPartner
  msix_version: 1.7.0.0
  logo_path: res/images/icon.png
  trim_logo: false