name: Build CF Partner Releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Flutter for Windows
        run: flutter config --enable-windows-desktop

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

  # build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.22.2'

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Set up Flutter for Linux
  #       run: flutter config --enable-linux-desktop

  #     - name: Patch for linux build
  #       run: |
  #         flutter doctor
  #         sudo apt-get update -y
  #         sudo apt-get install -y ninja-build libgtk-3-dev
  #         flutter doctor

  #     - name: Build Linux App
  #       run: flutter build linux

  #     - name: Upload Linux Build Artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: linux-build
  #         path: build/linux/ 

  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.22.2'

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Set up Flutter for macOS
  #       run: flutter config --enable-macos-desktop

  #     - name: Build macOS App
  #       run: flutter build macos

  #     - name: Upload macOS Build Artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: macos-build
  #         path: build/macos/Build/Products/Release/
